matrix:
  include:
  - language: node_js
    node_js:
    - '8'
    before_install: cd Node
  - &py-ci
    language: python
    python: '3.7'
    env:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_PYUP_API_KEY=""
    before_install: cd Python
    install:
    - pipenv sync --dev
    - pipenv check
    script:
    - PYTHONPATH=. pipenv run ci
